Just a bit more cleanup

diff --git a/testsuite/scalar/run_tests b/testsuite/scalar/run_tests
--- a/testsuite/scalar/run_tests
+++ b/testsuite/scalar/run_tests
@@ -1,21 +1,20 @@
 #!/bin/bash
 # This script needs to be run from the testsuite/scalar directory
 
-# Require user to specify both directory and target
-if [ $# -lt 4 ]; then
+# Currently only one application directory and target
+# User just needs to specify NCOL, DIMF and fermion irrep
+if [ $# -lt 2 ]; then
   echo "Try these:"
-  echo "./run_tests clover_hmc hmc 3 3 fundamental"
-  echo "./run_tests clover_hmc hmc 3 6 symmetric2"
-  echo "./run_tests clover_hmc hmc 4 4 fundamental"
-  echo "./run_tests clover_hmc hmc 4 6 antisymmetric2"
+  echo "./run_tests 3 3 fundamental"
+  echo "./run_tests 3 6 symmetric2"
+  echo "./run_tests 4 4 fundamental"
+  echo "./run_tests 4 6 antisymmetric2"
   exit 0
 fi
 
-dir=$1
-target=$2
-N=$3
-DIMF=$4
-rep=$5
+N=$1
+DIMF=$2
+rep=$3
 
 if [[ "$rep" == "fundamental" ]] ; then
   tag='F'
@@ -29,23 +28,23 @@ else
 fi
 
 # Change N and rep
-# TODO: Also need different fermion_rep_*.o in $dir/Make_template
+# TODO: Also need different fermion_rep_*.o in clover_hmc/Make_template
 cd ../../include/
 awk -v"X=#define NCOL $N" '{sub(/^#define NCOL .*/,X);print}' su3.h > TEMP && mv TEMP su3.h
 awk -v"X=#define DIMF $DIMF" '{sub(/^#define DIMF .*/,X);print}' su3.h > TEMP && mv TEMP su3.h
 awk -v"X=#define FREP $rep" '{sub(/^#define FREP .*/,X);print}' su3.h > TEMP && mv TEMP su3.h
 
 # Compile
-cd ../$dir/
-echo "Compiling su3_$target..."
-if ! make -f Make_scalar su3_$target >& /dev/null ; then
-  echo "ERROR: su3_$target compilation failed"
-  make -f Make_scalar su3_$target
+cd ../clover_hmc/
+echo "Compiling su3_hmc..."
+if ! make -f Make_scalar su3_hmc >& /dev/null ; then
+  echo "ERROR: su3_hmc compilation failed"
+  make -f Make_scalar su3_hmc
   exit
 fi
 
 # Reset N and rep to SU(3) fundamental
-# TODO: Also need different fermion_rep_*.o in $dir/Make_template
+# TODO: Also need different fermion_rep_*.o in clover_hmc/Make_template
 cd ../include/
 awk -v"X=#define NCOL 3" '{sub(/^#define NCOL .*/,X);print}' su3.h > TEMP && mv TEMP su3.h
 awk -v"X=#define DIMF 3" '{sub(/^#define DIMF .*/,X);print}' su3.h > TEMP && mv TEMP su3.h
@@ -53,17 +52,17 @@ awk -v"X=#define FREP fundamental" '{sub(/^#define FREP .*/,X);print}' su3.h > T
 
 # Run
 cd ../testsuite/
-rm -f scalar/$target.$N$tag.out
-echo "Running su3_$target..."
-../$dir/su3_$target < in.$N$tag.$target > scalar/$target.$N$tag.out
+rm -f scalar/hmc.$N$tag.out
+echo "Running su3_hmc..."
+../clover_hmc/su3_hmc < in.$N$tag.hmc > scalar/hmc.$N$tag.out
 
 # Check
 cd scalar/
-d="`diff -I'Time' -I'time' -I'seconds' -I'secs' -I'^start' -I'^exit:' $target.$N$tag.ref $target.$N$tag.out`"
+d="`diff -I'Time' -I'time' -I'seconds' -I'secs' -I'^start' -I'^exit:' hmc.$N$tag.ref hmc.$N$tag.out`"
 if [ -n "$d" ] ; then   # Non-zero string length
-  echo "$target.$N$tag.ref and $target.$N$tag.out differ:"
+  echo "hmc.$N$tag.ref and hmc.$N$tag.out differ:"
   echo "$d"
 else
-  echo "PASS: su3_$target reproduces reference output"
+  echo "PASS: su3_hmc reproduces reference output for SU($N) $rep"
 fi
 exit
